{% set name = "ldaptor" %}
{% set version = "20.1.0" %}
{% set sha256 = "5f7da3aaf00fa8ba3329e9d5c6ee3f66868ca2e5bf935f7b2537701a3ee01597" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - passlib
    - pip
    - pyparsing
    - python
    - setuptools
    - twisted
    - zope.interface

  run:
    - python
    - twisted
    - pyparsing
    - zope.interface

test:
  imports:
    - ldaptor
    - ldaptor.protocols
    - ldaptor.protocols.ldap
    - ldaptor.protocols.ldap.autofill
    - ldaptor.samba
    - ldaptor.test

about:
  home: https://github.com/twisted/ldaptor
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: A Pure-Python Twisted library for LDAP

extra:
  recipe-maintainers:
    - stuertz
