{% set name = "ldaptor" %}
{% set version = "19.1.0" %}
{% set sha256 = "64c7b870c77e34e4f5f9cfdf330b9702e89b4dd0f64275704f86c1468312c755" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
    - pycrypto
    # FIXME: Build currently against previous twisted version, because of
    # https://groups.google.com/a/continuum.io/forum/?fromgroups#!topic/anaconda/2_YQ3jGU1RQ 
    - twisted <17.1.0
    - pyopenssl
    - pyparsing
    - zope.interface

  run:
    - python
    - pycrypto
    # FIXME: see above
    - twisted <17.1.0
    - pyopenssl
    - pyparsing
    - zope.interface

test:
  imports:
    - ldaptor
    - ldaptor.protocols
    - ldaptor.protocols.ldap
    - ldaptor.protocols.ldap.autofill
    - ldaptor.samba
    - ldaptor.test

about:
  home: https://github.com/twisted/ldaptor
  license: MIT
  license_family: MIT
  summary: 'A Pure-Python Twisted library for LDAP'

extra:
  recipe-maintainers:
    - stuertz
