travis:
  secure:
    BINSTAR_TOKEN: fFnJDRo2zPs11jOgMi2ejJsYEAHTOGiNvWrSX0+FQOnpBCyyjaBJGGVK0Z87DtN1mzG5pJqrKkhNb7haisVT4nZ+3xqYQtyynDjpAQOeEc6LZ5ltRFM9hxw3jSyLV8Nv/sJVc1DtvOJxfoXLhzgsI+O/mpNS/ljDUdhkQibdZN7To4oVDLNYwYHYfUR41l5r8jf4Q9dW2TTFKD2QIifT4s5ABIrGGGrJu2M9Q3o5YHlFMIlVIIimr6y86Oizx+DDc6QCxTgkSsm5u7BjCmutKs+j3FZWzlejsVzvowMAnHyG2vzGOFXl2u/M/l5mcZ06eCF41z2FzNkKuCcdciJVwNyTKQ93uFI1PbMc4yuDSe6uYKBWUMRWKVJ6ii6yjvMoKtD07tD5bqvkiuYc4/Cwp2z1o4o7Ax9xyvfMEK/NFYlmpoVXJndrWpiXYyBtFcbBX3vUAjvVk+rsKbvvP8ugUKif688D5Sm0NGC4Lc1crMK2xgJ51wvJtxBB8OGRRES9+noHhCJ+IuZrnAG+Wt8s8M8VUL4RsqTDRdAydSyRq1Ohvo4uPqFyo79ypa6/yODVFE0B6cYLmFCliAPuX/u3x0fFJq82ve7enxaStm6+5yvnN5byPmGmOe2JjzxtPsSJ5y+QR+1eiPZ50tWGpGrFL/BCZXpd9ahERGtb0fv1qII=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
