travis:
  secure:
    BINSTAR_TOKEN: Aipcu7RHwXJZwESAxW7+s+GT8YKKlxyP3SYXtou0j+UPYZYmNMpSC6Vy2AK1fvYFGPbV6chZTWIcJCD7n0/bDslSL+dnGql6Aqb+UTXkni51Yoe+dhTExfqAS4GZgQVwA0rh+9XOdV9F2b6UlnlRuj1uKBfftwsZaIx+qLYUF1z3IUHQGnTwWcZQqQfNPNB/O1gpjGPZW6envTxnCIw8IO/L/+IbN9hCUblAC0Ub3kmDH2V0g08jDuoPzlxuHRh8r6x0msidZagTZPm84hcyWHGl3XrjtJurksLtJ8pXKIjGSw1RwR5GjB84w/FFkQuKQnZxxJ9Vlecj1BacX1jSSi3iq1MInciQtddOipcbUaPnDQvuLvxVmvm364TF4br5UA1IOvm+HqXoFbXV62cmuMmMS89WsXMDWGA/kZieJjdfPoKkQgF4SdV8WZXFg77V6x/zQI4IZ4wHF/nEZgJ+nno9MZ7WXfi0/bhaX13Tw8JjsfxKZGgRn96rcMq84hSVIJFtDIu5d8luRvC0sFgrkgnXC3EaQIy4WOeEVc9/YlXkhLP5RV/N3Xw7OyWR+tQSAEQVog9KTm9FaZcmdj8q5kah3RIql4EskCCyDNkyru2M9DHeH1SG+cn48w4qi0Mz3vKsJ5ewdRKEGbfXpYRKgdotdW2lLDpOnxq1vXN3IRg=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
