travis:
  secure:
    BINSTAR_TOKEN: J3SJY9HLlqM81WG1wgHM1d+vsr/CFe2oLHzm5br+vWhQ/z46vUqurQmYnNGSBAExAiP1Vh+NZFTuenjZOdbOqNxWgHy859xuvpwQ7KWl0gneOLJxPOWmiT9VYdSXyjUtPtgEvwBB7y8WQSFyWeihoc67ThJpVhAyG5W5Wg894ZKhuNAc7Mu4CEjr1KSN/l1Qt8nL1HJp+1/kjedb2RI7BaKnGl1gYF75ic2MhevxGS27aSVX9DhCMCNqimE0oGjhJejEMUmt/3YV/vWFS3aFpnFCNsF9JDrtn+A+aacSZCPi0xRp2cA9ljKLFxBw1BHrFbylYCMFCunShzbotGwZrmszgj763wyFpOohTNkFQb0ak0Evv39d8ykW36fpZskxoIsm8VqrsTj4kArlfwHvDLT/GvkuH/wsocI73jtUKunwDAb3t7ou7Cmyvr/6pYZmq9xu1b14072LbQVH+f7RlDfgtlvaoFD6LMP2T/MCNzXLC6Uz91bNyGQVfgBVE0XEAAk37JGWJHhNdmWjichFE94mUwHQ44otey0pyAN1/VIfQTe9zIxu+RVntYDxrA2e27HyMeo3+Tp6gtcFUcePFFrNZE8EgKIo1fBk4wBuYqOQ6DRRBz6iBT3d0cZJYymMVDHNK/FzPR7D4/W8UXxm3u+LHf+ABfGW/C4GC27nX40=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
