travis:
  secure:
    BINSTAR_TOKEN: T0txS61rKjEfJ3zPaxp6jDV5omf2It4ZdpC4l0aTiuvkOAdtpHGwZfBjR/JhjOO9TygpE9ZGPe3PsQZa5Ydz+JTzcj6DvvCgCHj6SQu4C5wLlqm4xT8nsPGpFr1UWnLqjsEYJKhPrX7kMP+9Cq7KhTxKhkBfRLR65ax3RaBJQOurr5AXEqvaBcJbsW1zSLQ08cjcMfdqO57WOVzkd4qGlr5KypgSIisEGcNiHFNS398dK69lhf4h08Z96QXLmFznQ2NvBmw6r3rHI0Bex+2sSxfw+HEwtN1cx2JOrTmLb05UDY6VL9R6uMqNMX8IPiz5Z6MEFXCis06vUvlT+crQDwBWMAWpj9hblioo5ZU/HkkhnFq3luQY8WmjTLGNJNuC2Q7afAKzu43Fy9/PHoyAB0dLTI1+N799oUe3FrQjIJlzswizYua+cfEwuHJmH7pL2VRe0CgrRS+r7nnfWr9fDQTNNl0trPcTyxvZanBtucy0BMI6qCie33IIJsoAC0WhCWa9993g4Q/Vlv+5FOW7mtn6RNcCr++aNoJeIAGMXgn6oZhZxLVTy6i7bPkGzXd8KkI/lfgFJfShoU7aDq+wU4vQtcyOEp1dJBza6TIgrOcVtNka0NDtmzppK7Q7j6xrM5Rto+2iTra+wc06F8r+qSvxlBtOOyFxaKCJMDxxN+w=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
