travis:
  secure:
    BINSTAR_TOKEN: bkSR4OcguyENR6zeZOi7krQnnyDdf5vXqbc+NUDGnR6TeqNiePoAGtTKcvEfmfFKlzBwle9+CYSQ80l1v2Nn5v2CsuWStCg9yUbfQb+KNlTNC85Bz93AJx+gaz6yzDaU4A7SnvDwrN0t8pU46lg/xlYglp70WnMEjOpqK/9DimrWejJdNvSrzIVCqTZ4nYP6wV4JlZGq/WexpptCjucyoA8Z8zU6kSiwWz5fLA/uK/CGuLyXHO7c3xArnrotUWe/KvsISJVKAVt+xwbe+ymGQEt6rSZj+4b93SMf1TeIppMXjZ9ZD7bLHlpgDAKOJ4nfnu3+5KpauTNANjjXYWNkh+Tol6k6f0oHtkOirvFSQqCRd5pECEQI6X9mYFuxT8U4tz5Lb6WHiu2cuKOZJJzXiApA3NhbE65hwUIlWnnl7YXMFjcFZv67aMbwYvZclSlCBnIFpRRcRS0h1uH4URC96zUlY5ZZvGDiGBrI8a9VoDGAG8mpPOFyLl3gEQXdp6GghzlqYrV1FASc4ZOXtM4TnCkQQ0oM5pe1YA9BX5aDGWx+8RYDbMs1GMNhY/NzPtTPa6gmlWxgDjL5mUTVLxOMsFTqFevWbwYrMcY3ekalf3y2uCqmXKbMvM2NeuAJ6LD3tn2rm/cd7STkPc6iUwE1pAzoape+pUtbXj/l7EMGR0A=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
